# Generated by Django 5.2.8 on 2025-12-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution_type',
            field=models.CharField(max_length=20),
        ),
    ]
