# Generated by Django 5.2.8 on 2025-12-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_is_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_or_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('university', 'University')], max_length=20),
        ),
    ]
